# Generated by Django 5.2.12 on 2026-03-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500, unique=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('match_score', models.IntegerField(default=0)),
                ('skills_found', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
