# Generated by Django 5.2.12 on 2026-03-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ai_advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='missing_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
